pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                echo 'Step 1 : Build Starts Now'
                sh 'mvn -B -DskipTests clean package'
                echo 'Step 1 : Build Ends'
                
            }
        }
        stage('Test') {
            steps {
                echo 'Step 2 : Test Starts'
                sh 'mvn test'
                echo 'Step 2 : Test Ends'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo 'Step 3 : Deliver Starts'
                sh './jenkins/scripts/deliver.sh'
                echo 'Step 3 : Deliver Ends'
            }
        }
    }
}
